openapi: 3.0.0
info:
  title: Your API Title
  description: Your API Description
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local Development Server
paths:
  /api/test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string